const FOOD_DATABASE = [
  // Viandes, volailles, charcuterie
  { name: 'Œuf entier', defaultPortion: 1, unit: 'pièce', kcal: 70, kcalPer100g: 143, portionDescription: '1 œuf moyen (~50g)', category: 'Protéines', aliases: ['oeuf', 'petit dej'] },
  { name: 'Blanc d\'œuf', defaultPortion: 1, unit: 'pièce', kcal: 17, kcalPer100g: 52, portionDescription: '1 blanc (~33g)', category: 'Protéines' },
  { name: 'Jambon blanc', defaultPortion: 1, unit: 'tranche', kcal: 42, kcalPer100g: 116, portionDescription: '1 tranche (~36g)', category: 'Charcuterie' },
  { name: 'Jambon cru', defaultPortion: 1, unit: 'tranche fine', kcal: 33, kcalPer100g: 247, portionDescription: '1 tranche fine (~13g)', category: 'Charcuterie' },
  { name: 'Blanc de poulet', defaultPortion: 120, unit: 'g', kcal: 198, kcalPer100g: 165, portionDescription: 'Escalope moyenne 120g', category: 'Protéines' },
  { name: 'Dinde', defaultPortion: 120, unit: 'g', kcal: 162, kcalPer100g: 135, portionDescription: 'Escalope moyenne 120g', category: 'Protéines' },
  { name: 'Steak haché 5%', defaultPortion: 100, unit: 'g', kcal: 137, kcalPer100g: 137, portionDescription: '1 steak 100g', category: 'Protéines' },
  { name: 'Steak haché 15%', defaultPortion: 100, unit: 'g', kcal: 215, kcalPer100g: 215, portionDescription: '1 steak 100g', category: 'Protéines' },
  { name: 'Escalope de veau', defaultPortion: 120, unit: 'g', kcal: 206, kcalPer100g: 172, portionDescription: '1 escalope 120g', category: 'Protéines' },
  { name: 'Tofu ferme', defaultPortion: 120, unit: 'g', kcal: 172, kcalPer100g: 143, portionDescription: '1 portion 120g', category: 'Protéines', aliases: ['vege', 'végétarien'] },
  { name: 'Bœuf (rumsteak)', defaultPortion: 120, unit: 'g', kcal: 205, kcalPer100g: 171, portionDescription: '1 pavé 120g', category: 'Protéines' },
  { name: 'Porc (côte)', defaultPortion: 150, unit: 'g', kcal: 363, kcalPer100g: 242, portionDescription: '1 côte 150g', category: 'Protéines' },
  { name: 'Bacon grillé', defaultPortion: 2, unit: 'tranche', kcal: 87, kcalPer100g: 541, portionDescription: '2 tranches grillées (~16g)', category: 'Charcuterie', aliases: ['petit dej'] },
  { name: 'Lardons fumés', defaultPortion: 75, unit: 'g', kcal: 233, kcalPer100g: 311, portionDescription: '1/2 barquette', category: 'Charcuterie' },
  { name: 'Lardons nature', defaultPortion: 75, unit: 'g', kcal: 210, kcalPer100g: 280, portionDescription: '1/2 barquette', category: 'Charcuterie' },
  { name: 'Saucisson sec', defaultPortion: 30, unit: 'g', kcal: 144, kcalPer100g: 480, portionDescription: '10 rondelles (~30g)', category: 'Charcuterie' },
  { name: 'Chipolata', defaultPortion: 1, unit: 'pièce', kcal: 188, kcalPer100g: 290, portionDescription: '1 pièce (~65g)', category: 'Charcuterie' },
  { name: 'Merguez', defaultPortion: 1, unit: 'pièce', kcal: 166, kcalPer100g: 320, portionDescription: '1 pièce (~52g)', category: 'Charcuterie' },

  // Poissons
  { name: 'Saumon', defaultPortion: 120, unit: 'g', kcal: 250, kcalPer100g: 208, portionDescription: 'Pavé 120g', category: 'Poissons' },
  { name: 'Thon naturel', defaultPortion: 100, unit: 'g', kcal: 116, kcalPer100g: 116, portionDescription: '1 portion égouttée', category: 'Poissons' },
  { name: 'Cabillaud', defaultPortion: 120, unit: 'g', kcal: 98, kcalPer100g: 82, portionDescription: 'Filet 120g', category: 'Poissons' },
  { name: 'Maquereau', defaultPortion: 100, unit: 'g', kcal: 205, kcalPer100g: 205, portionDescription: '1 filet', category: 'Poissons' },
  { name: 'Sardines à l\'huile', defaultPortion: 100, unit: 'g', kcal: 208, kcalPer100g: 208, portionDescription: '1 petite boîte', category: 'Poissons' },
  { name: 'Crevettes', defaultPortion: 100, unit: 'g', kcal: 99, kcalPer100g: 99, portionDescription: '12-15 crevettes', category: 'Poissons' },
  { name: 'Moules marinières', defaultPortion: 250, unit: 'g', kcal: 430, kcalPer100g: 172, portionDescription: '1 assiette', category: 'Poissons' },
  { name: 'Surimi', defaultPortion: 6, unit: 'pièce', kcal: 102, kcalPer100g: 110, portionDescription: '6 bâtonnets (~93g)', category: 'Poissons' },

  // Produits laitiers / fromages
  { name: 'Yaourt nature', defaultPortion: 1, unit: 'pot', kcal: 77, kcalPer100g: 62, portionDescription: '1 pot 125g', category: 'Laitiers' },
  { name: 'Yaourt grec', defaultPortion: 1, unit: 'pot', kcal: 155, kcalPer100g: 124, portionDescription: '1 pot 125g', category: 'Laitiers' },
  { name: 'Skyr', defaultPortion: 1, unit: 'pot', kcal: 90, kcalPer100g: 60, portionDescription: '1 pot 150g', category: 'Laitiers' },
  { name: 'Fromage blanc 0%', defaultPortion: 100, unit: 'g', kcal: 46, kcalPer100g: 46, portionDescription: '100g', category: 'Laitiers' },
  { name: 'Petit suisse', defaultPortion: 2, unit: 'pièce', kcal: 110, kcalPer100g: 92, portionDescription: '2 x 60g', category: 'Laitiers' },
  { name: 'Lait demi-écrémé', defaultPortion: 200, unit: 'ml', kcal: 94, kcalPer100g: 47, portionDescription: '1 verre 200ml', category: 'Boissons' },
  { name: 'Lait entier', defaultPortion: 200, unit: 'ml', kcal: 128, kcalPer100g: 64, portionDescription: '1 verre 200ml', category: 'Boissons' },
  { name: 'Boisson amande sans sucre', defaultPortion: 200, unit: 'ml', kcal: 26, kcalPer100g: 13, portionDescription: '1 verre 200ml', category: 'Boissons' },
  { name: 'Beurre', defaultPortion: 10, unit: 'g', kcal: 75, kcalPer100g: 750, portionDescription: '1 noisette (10g)', category: 'Matières grasses' },
  { name: 'Crème fraîche entière', defaultPortion: 1, unit: 'cs', kcal: 51, kcalPer100g: 340, portionDescription: '1 càs (~15g)', category: 'Sauces' },
  { name: 'Crème fraîche légère', defaultPortion: 1, unit: 'cs', kcal: 30, kcalPer100g: 200, portionDescription: '1 càs (~15g)', category: 'Sauces' },
  { name: 'Fromage emmental', defaultPortion: 30, unit: 'g', kcal: 114, kcalPer100g: 380, portionDescription: '1 portion 30g', category: 'Laitiers' },
  { name: 'Comté', defaultPortion: 30, unit: 'g', kcal: 126, kcalPer100g: 420, portionDescription: '1 portion 30g', category: 'Laitiers' },
  { name: 'Mozzarella', defaultPortion: 62, unit: 'g', kcal: 174, kcalPer100g: 280, portionDescription: '1/2 boule', category: 'Laitiers' },
  { name: 'Fromage de chèvre frais', defaultPortion: 30, unit: 'g', kcal: 84, kcalPer100g: 280, portionDescription: '2 rondelles fraîches', category: 'Laitiers', aliases: ['chevre'] },
  { name: 'Fromage de chèvre bûche (sec)', defaultPortion: 30, unit: 'g', kcal: 117, kcalPer100g: 390, portionDescription: '3 rondelles', category: 'Laitiers', aliases: ['chevre'] },
  { name: 'Camembert', defaultPortion: 30, unit: 'g', kcal: 90, kcalPer100g: 300, portionDescription: '1/8 camembert', category: 'Laitiers' },

  // Féculents / céréales
  { name: 'Riz blanc cuit', defaultPortion: 150, unit: 'g', kcal: 195, kcalPer100g: 130, portionDescription: '1 bol moyen', category: 'Féculents' },
  { name: 'Riz complet cuit', defaultPortion: 150, unit: 'g', kcal: 168, kcalPer100g: 112, portionDescription: '1 bol moyen', category: 'Féculents' },
  { name: 'Pâtes cuites', defaultPortion: 150, unit: 'g', kcal: 237, kcalPer100g: 158, portionDescription: '1 assiette', category: 'Féculents' },
  { name: 'Semoule cuite', defaultPortion: 150, unit: 'g', kcal: 168, kcalPer100g: 112, portionDescription: '1 bol moyen', category: 'Féculents' },
  { name: 'Quinoa cuit', defaultPortion: 150, unit: 'g', kcal: 180, kcalPer100g: 120, portionDescription: '1 bol moyen', category: 'Féculents' },
  { name: 'Lentilles cuites', defaultPortion: 150, unit: 'g', kcal: 174, kcalPer100g: 116, portionDescription: '1 bol', category: 'Légumineuses' },
  { name: 'Pois chiches cuits', defaultPortion: 150, unit: 'g', kcal: 246, kcalPer100g: 164, portionDescription: '1 bol', category: 'Légumineuses' },
  { name: 'Haricots rouges cuits', defaultPortion: 150, unit: 'g', kcal: 191, kcalPer100g: 127, portionDescription: '1 bol', category: 'Légumineuses' },
  { name: 'Pommes de terre vapeur', defaultPortion: 200, unit: 'g', kcal: 172, kcalPer100g: 86, portionDescription: '2 pommes de terre', category: 'Féculents' },
  { name: 'Purée maison', defaultPortion: 200, unit: 'g', kcal: 180, kcalPer100g: 90, portionDescription: '1 assiette', category: 'Féculents' },
  { name: 'Patate douce cuite', defaultPortion: 200, unit: 'g', kcal: 180, kcalPer100g: 90, portionDescription: '1 moyenne', category: 'Féculents' },
  { name: 'Pain complet', defaultPortion: 1, unit: 'tranche', kcal: 98, kcalPer100g: 245, portionDescription: '1 tranche (~40g)', category: 'Féculents' },
  { name: 'Pain blanc', defaultPortion: 1, unit: 'tranche', kcal: 80, kcalPer100g: 266, portionDescription: '1 tranche (~30g)', category: 'Féculents' },
  { name: 'Pain de mie nature', defaultPortion: 1, unit: 'tranche', kcal: 70, kcalPer100g: 250, portionDescription: '1 tranche moyenne (~28g)', category: 'Féculents', aliases: ['pain', 'tranche'] },
  { name: 'Pain de mie complet', defaultPortion: 1, unit: 'tranche', kcal: 68, kcalPer100g: 245, portionDescription: '1 tranche moyenne (~28g)', category: 'Féculents', aliases: ['pain', 'tranche'] },
  { name: 'Pain de mie (tranche fine)', defaultPortion: 1, unit: 'tranche fine', kcal: 52, kcalPer100g: 250, portionDescription: '1 tranche fine (~21g)', category: 'Féculents', aliases: ['pain de mie', 'tranche fine'] },
  { name: 'Pain de mie (tranche épaisse)', defaultPortion: 1, unit: 'tranche épaisse', kcal: 95, kcalPer100g: 250, portionDescription: '1 tranche épaisse (~38g)', category: 'Féculents', aliases: ['pain de mie', 'tranche epaisse'] },
  { name: 'Baguette', defaultPortion: 1, unit: 'tranche', kcal: 93, kcalPer100g: 265, portionDescription: '1/6 baguette (~35g)', category: 'Féculents' },
  { name: 'Pâtes complètes cuites', defaultPortion: 150, unit: 'g', kcal: 210, kcalPer100g: 140, portionDescription: '1 assiette', category: 'Féculents' },
  { name: 'Tortilla blé', defaultPortion: 1, unit: 'pièce', kcal: 160, kcalPer100g: 320, portionDescription: '1 wrap (~50g)', category: 'Féculents' },
  { name: 'Flocons d\'avoine', defaultPortion: 40, unit: 'g', kcal: 150, kcalPer100g: 375, portionDescription: '4 càs bombées', category: 'Petit-déjeuner' },
  { name: 'Muesli', defaultPortion: 45, unit: 'g', kcal: 170, kcalPer100g: 378, portionDescription: '1 bol petit-déj', category: 'Petit-déjeuner' },
  { name: 'Corn flakes', defaultPortion: 30, unit: 'g', kcal: 113, kcalPer100g: 377, portionDescription: '1 bol', category: 'Petit-déjeuner' },

  // Légumes
  { name: 'Brocoli', defaultPortion: 150, unit: 'g', kcal: 53, kcalPer100g: 35, portionDescription: '1 portion cuite', category: 'Légumes' },
  { name: 'Haricots verts', defaultPortion: 150, unit: 'g', kcal: 47, kcalPer100g: 31, portionDescription: '1 portion', category: 'Légumes' },
  { name: 'Courgette', defaultPortion: 150, unit: 'g', kcal: 26, kcalPer100g: 17, portionDescription: '1 courgette', category: 'Légumes' },
  { name: 'Carotte', defaultPortion: 120, unit: 'g', kcal: 49, kcalPer100g: 41, portionDescription: '2 carottes', category: 'Légumes' },
  { name: 'Tomate', defaultPortion: 1, unit: 'pièce', kcal: 22, kcalPer100g: 18, portionDescription: '1 tomate moyenne (~120g)', category: 'Légumes' },
  { name: 'Concombre', defaultPortion: 150, unit: 'g', kcal: 23, kcalPer100g: 15, portionDescription: '1/2 concombre', category: 'Légumes' },
  { name: 'Épinards cuits', defaultPortion: 150, unit: 'g', kcal: 35, kcalPer100g: 23, portionDescription: '1 portion', category: 'Légumes' },
  { name: 'Poêlée de légumes', defaultPortion: 200, unit: 'g', kcal: 110, kcalPer100g: 55, portionDescription: '1 assiette', category: 'Légumes' },
  { name: 'Salade verte', defaultPortion: 80, unit: 'g', kcal: 12, kcalPer100g: 15, portionDescription: '1 bol', category: 'Légumes' },
  { name: 'Avocat', defaultPortion: 0.5, unit: '1/2', kcal: 128, kcalPer100g: 160, portionDescription: '1/2 avocat (~80g)', category: 'Fruits', aliases: ['demi'] },

  // Fruits
  { name: 'Banane', defaultPortion: 1, unit: 'pièce', kcal: 105, kcalPer100g: 89, portionDescription: '1 banane moyenne (~118g)', category: 'Fruits' },
  { name: 'Pomme', defaultPortion: 1, unit: 'pièce', kcal: 80, kcalPer100g: 52, portionDescription: '1 pomme moyenne (~154g)', category: 'Fruits' },
  { name: 'Framboises', defaultPortion: 125, unit: 'g', kcal: 65, kcalPer100g: 52, portionDescription: '1 barquette', category: 'Fruits' },
  { name: 'Mangue', defaultPortion: 150, unit: 'g', kcal: 90, kcalPer100g: 60, portionDescription: '1/2 mangue', category: 'Fruits' },
  { name: 'Poire', defaultPortion: 1, unit: 'pièce', kcal: 85, kcalPer100g: 57, portionDescription: '1 poire moyenne', category: 'Fruits' },
  { name: 'Orange', defaultPortion: 1, unit: 'pièce', kcal: 62, kcalPer100g: 47, portionDescription: '1 orange moyenne', category: 'Fruits' },
  { name: 'Kiwi', defaultPortion: 1, unit: 'pièce', kcal: 46, kcalPer100g: 61, portionDescription: '1 kiwi (~75g)', category: 'Fruits' },
  { name: 'Fraises', defaultPortion: 150, unit: 'g', kcal: 48, kcalPer100g: 32, portionDescription: '1 bol', category: 'Fruits' },
  { name: 'Myrtilles', defaultPortion: 125, unit: 'g', kcal: 71, kcalPer100g: 57, portionDescription: '1 barquette', category: 'Fruits' },
  { name: 'Raisin', defaultPortion: 100, unit: 'g', kcal: 69, kcalPer100g: 69, portionDescription: '1 petite grappe', category: 'Fruits' },
  { name: 'Ananas', defaultPortion: 150, unit: 'g', kcal: 75, kcalPer100g: 50, portionDescription: '2 tranches', category: 'Fruits' },
  { name: 'Compote sans sucre', defaultPortion: 100, unit: 'g', kcal: 68, kcalPer100g: 68, portionDescription: '1 pot', category: 'Desserts' },

  // Sauces / condiments / matières grasses
  { name: 'Huile d\'olive', defaultPortion: 1, unit: 'cs', kcal: 90, kcalPer100g: 900, portionDescription: '1 càs (~10g)', category: 'Matières grasses' },
  { name: 'Huile de colza', defaultPortion: 1, unit: 'cs', kcal: 90, kcalPer100g: 900, portionDescription: '1 càs (~10g)', category: 'Matières grasses' },
  { name: 'Vinaigrette maison', defaultPortion: 1, unit: 'cs', kcal: 75, kcalPer100g: 500, portionDescription: '1 càs (~15g)', category: 'Sauces' },
  { name: 'Ketchup', defaultPortion: 1, unit: 'cs', kcal: 17, kcalPer100g: 112, portionDescription: '1 càs (~15g)', category: 'Sauces', aliases: ['sauce'] },
  { name: 'Mayonnaise', defaultPortion: 1, unit: 'cs', kcal: 102, kcalPer100g: 680, portionDescription: '1 càs (~15g)', category: 'Sauces', aliases: ['sauce', 'mayo'] },
  { name: 'Moutarde', defaultPortion: 1, unit: 'cc', kcal: 5, kcalPer100g: 66, portionDescription: '1 càc (~8g)', category: 'Sauces' },
  { name: 'Sauce barbecue', defaultPortion: 1, unit: 'cs', kcal: 25, kcalPer100g: 165, portionDescription: '1 càs (~15g)', category: 'Sauces' },
  { name: 'Sauce soja salée', defaultPortion: 1, unit: 'cs', kcal: 8, kcalPer100g: 53, portionDescription: '1 càs (~15ml)', category: 'Sauces' },
  { name: 'Pesto', defaultPortion: 1, unit: 'cs', kcal: 72, kcalPer100g: 480, portionDescription: '1 càs (~15g)', category: 'Sauces' },
  { name: 'Confiture', defaultPortion: 1, unit: 'cs', kcal: 39, kcalPer100g: 260, portionDescription: '1 càs (~15g)', category: 'Sucré' },
  { name: 'Miel', defaultPortion: 1, unit: 'cs', kcal: 46, kcalPer100g: 304, portionDescription: '1 càs (~15g)', category: 'Sucré' },
  { name: 'Sucre', defaultPortion: 1, unit: 'cc', kcal: 16, kcalPer100g: 400, portionDescription: '1 càc (~4g)', category: 'Sucré' },

  // Sucré / snacks
  { name: 'Amandes', defaultPortion: 30, unit: 'g', kcal: 174, kcalPer100g: 579, portionDescription: '1 poignée', category: 'Snacks' },
  { name: 'Noix', defaultPortion: 30, unit: 'g', kcal: 196, kcalPer100g: 654, portionDescription: '1 poignée', category: 'Snacks' },
  { name: 'Cacahuètes grillées', defaultPortion: 30, unit: 'g', kcal: 170, kcalPer100g: 567, portionDescription: '1 poignée', category: 'Snacks' },
  { name: 'Beurre de cacahuète', defaultPortion: 1, unit: 'cs', kcal: 94, kcalPer100g: 588, portionDescription: '1 càs (~16g)', category: 'Snacks' },
  { name: 'Noisettes', defaultPortion: 30, unit: 'g', kcal: 188, kcalPer100g: 628, portionDescription: '1 poignée', category: 'Snacks' },
  { name: 'Chocolat noir 70%', defaultPortion: 20, unit: 'g', kcal: 120, kcalPer100g: 600, portionDescription: '2 carrés', category: 'Sucré' },
  { name: 'Chocolat au lait', defaultPortion: 20, unit: 'g', kcal: 107, kcalPer100g: 535, portionDescription: '2 carrés', category: 'Sucré' },
  { name: 'Biscuit sablé', defaultPortion: 2, unit: 'pièce', kcal: 96, kcalPer100g: 480, portionDescription: '2 biscuits (~20g)', category: 'Sucré' },
  { name: 'Barre chocolatée', defaultPortion: 1, unit: 'pièce', kcal: 230, kcalPer100g: 500, portionDescription: '1 barre (46g)', category: 'Sucré' },
  { name: 'Croissant', defaultPortion: 1, unit: 'pièce', kcal: 231, kcalPer100g: 420, portionDescription: '1 croissant 55g', category: 'Petit-déjeuner' },
  { name: 'Pain au chocolat', defaultPortion: 1, unit: 'pièce', kcal: 330, kcalPer100g: 440, portionDescription: '1 pièce 75g', category: 'Petit-déjeuner' },
  { name: 'Crêpe nature', defaultPortion: 1, unit: 'pièce', kcal: 112, kcalPer100g: 224, portionDescription: '1 crêpe 50g', category: 'Desserts' },
  { name: 'Glace vanille', defaultPortion: 2, unit: 'boule', kcal: 180, kcalPer100g: 207, portionDescription: '2 boules (~87g)', category: 'Desserts' },

  // Boissons
  { name: 'Eau', defaultPortion: 250, unit: 'ml', kcal: 0, kcalPer100g: 0, portionDescription: '1 verre', category: 'Boissons' },
  { name: 'Café sans sucre', defaultPortion: 1, unit: 'tasse', kcal: 2, kcalPer100g: 1, portionDescription: '1 tasse 150ml', category: 'Boissons' },
  { name: 'Thé sans sucre', defaultPortion: 1, unit: 'tasse', kcal: 2, kcalPer100g: 1, portionDescription: '1 tasse 150ml', category: 'Boissons' },
  { name: 'Jus d\'orange', defaultPortion: 200, unit: 'ml', kcal: 90, kcalPer100g: 45, portionDescription: '1 verre', category: 'Boissons' },
  { name: 'Soda cola', defaultPortion: 330, unit: 'ml', kcal: 139, kcalPer100g: 42, portionDescription: '1 canette', category: 'Boissons' },
  { name: 'Soda zéro', defaultPortion: 330, unit: 'ml', kcal: 3, kcalPer100g: 1, portionDescription: '1 canette', category: 'Boissons' },
  { name: 'Smoothie fruits', defaultPortion: 250, unit: 'ml', kcal: 150, kcalPer100g: 60, portionDescription: '1 bouteille', category: 'Boissons' },
  { name: 'Bière blonde', defaultPortion: 250, unit: 'ml', kcal: 108, kcalPer100g: 43, portionDescription: '1 demi', category: 'Boissons' },
  { name: 'Vin rouge', defaultPortion: 150, unit: 'ml', kcal: 127, kcalPer100g: 85, portionDescription: '1 verre', category: 'Boissons' },
  { name: 'Champagne', defaultPortion: 120, unit: 'ml', kcal: 102, kcalPer100g: 85, portionDescription: '1 flûte', category: 'Boissons' },

  // Plats préparés / fast-food
  { name: 'Pizza margherita', defaultPortion: 300, unit: 'g', kcal: 780, kcalPer100g: 260, portionDescription: '1/2 pizza', category: 'Plats préparés' },
  { name: 'Burger classique', defaultPortion: 1, unit: 'pièce', kcal: 450, kcalPer100g: 250, portionDescription: '1 burger (~180g)', category: 'Plats préparés' },
  { name: 'Cheeseburger', defaultPortion: 1, unit: 'pièce', kcal: 303, kcalPer100g: 253, portionDescription: '1 pièce (~120g)', category: 'Plats préparés' },
  { name: 'Frites', defaultPortion: 150, unit: 'g', kcal: 468, kcalPer100g: 312, portionDescription: '1 portion moyenne', category: 'Plats préparés' },
  { name: 'Nuggets de poulet', defaultPortion: 6, unit: 'pièce', kcal: 285, kcalPer100g: 285, portionDescription: '6 nuggets (~100g)', category: 'Plats préparés' },
  { name: 'Wrap poulet', defaultPortion: 1, unit: 'pièce', kcal: 420, kcalPer100g: 191, portionDescription: '1 wrap (~220g)', category: 'Plats préparés' },
  { name: 'Sushi saumon (6)', defaultPortion: 1, unit: 'portion', kcal: 220, kcalPer100g: 122, portionDescription: '6 pièces (~180g)', category: 'Plats préparés' },
  { name: 'Quiche lorraine', defaultPortion: 1, unit: 'part', kcal: 360, kcalPer100g: 300, portionDescription: '1 part (~120g)', category: 'Plats préparés' },
  { name: 'Lasagnes bolognaise', defaultPortion: 300, unit: 'g', kcal: 480, kcalPer100g: 160, portionDescription: '1 portion', category: 'Plats préparés' },
  { name: 'Soupe de légumes', defaultPortion: 300, unit: 'ml', kcal: 90, kcalPer100g: 30, portionDescription: '1 bol', category: 'Plats préparés' }
];
