const FOOD_DATABASE = [
  { name: 'Œuf entier', defaultPortionG: 50, kcalPerPortion: 70, protein: 6.3, carbs: 0.4, fat: 4.8 },
  { name: 'Blanc d\'œuf', defaultPortionG: 33, kcalPerPortion: 17, protein: 3.6, carbs: 0.2, fat: 0.1 },
  { name: 'Jambon blanc', defaultPortionG: 30, kcalPerPortion: 45, protein: 7.0, carbs: 0.3, fat: 1.5 },
  { name: 'Poulet grillé', defaultPortionG: 100, kcalPerPortion: 165, protein: 31, carbs: 0, fat: 3.6 },
  { name: 'Dinde', defaultPortionG: 100, kcalPerPortion: 135, protein: 29, carbs: 0, fat: 1.6 },
  { name: 'Steak haché 5%', defaultPortionG: 100, kcalPerPortion: 137, protein: 21, carbs: 0, fat: 5 },
  { name: 'Saumon', defaultPortionG: 100, kcalPerPortion: 208, protein: 20, carbs: 0, fat: 13 },
  { name: 'Thon naturel', defaultPortionG: 100, kcalPerPortion: 116, protein: 26, carbs: 0, fat: 1 },
  { name: 'Cabillaud', defaultPortionG: 100, kcalPerPortion: 82, protein: 18, carbs: 0, fat: 0.7 },
  { name: 'Lentilles cuites', defaultPortionG: 100, kcalPerPortion: 116, protein: 9, carbs: 20, fat: 0.4 },
  { name: 'Pois chiches cuits', defaultPortionG: 100, kcalPerPortion: 164, protein: 8.9, carbs: 27, fat: 2.6 },
  { name: 'Haricots rouges', defaultPortionG: 100, kcalPerPortion: 127, protein: 8.7, carbs: 23, fat: 0.5 },
  { name: 'Riz blanc cuit', defaultPortionG: 100, kcalPerPortion: 130, protein: 2.4, carbs: 28, fat: 0.3 },
  { name: 'Riz complet cuit', defaultPortionG: 100, kcalPerPortion: 112, protein: 2.6, carbs: 23, fat: 0.9 },
  { name: 'Pâtes cuites', defaultPortionG: 100, kcalPerPortion: 158, protein: 5.8, carbs: 31, fat: 0.9 },
  { name: 'Quinoa cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 4.4, carbs: 21, fat: 1.9 },
  { name: 'Semoule cuite', defaultPortionG: 100, kcalPerPortion: 112, protein: 3.8, carbs: 23, fat: 0.2 },
  { name: 'Pain complet', defaultPortionG: 40, kcalPerPortion: 98, protein: 4.2, carbs: 16, fat: 1.3 },
  { name: 'Pain blanc', defaultPortionG: 40, kcalPerPortion: 106, protein: 3.2, carbs: 20, fat: 0.9 },
  { name: 'Flocons d\'avoine', defaultPortionG: 40, kcalPerPortion: 150, protein: 5.2, carbs: 25, fat: 3 },
  { name: 'Muesli', defaultPortionG: 45, kcalPerPortion: 170, protein: 4.5, carbs: 28, fat: 4 },
  { name: 'Banane', defaultPortionG: 120, kcalPerPortion: 105, protein: 1.3, carbs: 27, fat: 0.3 },
  { name: 'Pomme', defaultPortionG: 150, kcalPerPortion: 78, protein: 0.4, carbs: 21, fat: 0.3 },
  { name: 'Poire', defaultPortionG: 150, kcalPerPortion: 85, protein: 0.6, carbs: 23, fat: 0.2 },
  { name: 'Orange', defaultPortionG: 130, kcalPerPortion: 62, protein: 1.2, carbs: 15, fat: 0.2 },
  { name: 'Fraises', defaultPortionG: 150, kcalPerPortion: 48, protein: 1, carbs: 11, fat: 0.4 },
  { name: 'Myrtilles', defaultPortionG: 100, kcalPerPortion: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { name: 'Avocat', defaultPortionG: 100, kcalPerPortion: 160, protein: 2, carbs: 9, fat: 15 },
  { name: 'Amandes', defaultPortionG: 30, kcalPerPortion: 174, protein: 6.4, carbs: 6.5, fat: 15 },
  { name: 'Noix', defaultPortionG: 30, kcalPerPortion: 196, protein: 4.5, carbs: 4, fat: 19.5 },
  { name: 'Beurre de cacahuète', defaultPortionG: 20, kcalPerPortion: 118, protein: 5, carbs: 3, fat: 10 },
  { name: 'Yaourt nature', defaultPortionG: 125, kcalPerPortion: 78, protein: 5, carbs: 6, fat: 3.5 },
  { name: 'Skyr', defaultPortionG: 150, kcalPerPortion: 90, protein: 16, carbs: 6, fat: 0.3 },
  { name: 'Fromage blanc 0%', defaultPortionG: 100, kcalPerPortion: 46, protein: 8.5, carbs: 4, fat: 0.2 },
  { name: 'Lait demi-écrémé', defaultPortionG: 200, kcalPerPortion: 94, protein: 6.8, carbs: 9.4, fat: 3 },
  { name: 'Lait d\'amande', defaultPortionG: 200, kcalPerPortion: 30, protein: 1, carbs: 1, fat: 2.6 },
  { name: 'Fromage emmental', defaultPortionG: 30, kcalPerPortion: 114, protein: 8, carbs: 0.5, fat: 9 },
  { name: 'Mozzarella', defaultPortionG: 60, kcalPerPortion: 168, protein: 13, carbs: 1.6, fat: 12 },
  { name: 'Huile d\'olive', defaultPortionG: 10, kcalPerPortion: 90, protein: 0, carbs: 0, fat: 10 },
  { name: 'Beurre', defaultPortionG: 10, kcalPerPortion: 75, protein: 0.1, carbs: 0, fat: 8.2 },
  { name: 'Pomme de terre cuite', defaultPortionG: 150, kcalPerPortion: 129, protein: 3, carbs: 30, fat: 0.2 },
  { name: 'Patate douce cuite', defaultPortionG: 150, kcalPerPortion: 135, protein: 2.5, carbs: 31, fat: 0.2 },
  { name: 'Brocoli', defaultPortionG: 100, kcalPerPortion: 35, protein: 2.8, carbs: 7, fat: 0.4 },
  { name: 'Courgette', defaultPortionG: 100, kcalPerPortion: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { name: 'Carotte', defaultPortionG: 100, kcalPerPortion: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { name: 'Tomate', defaultPortionG: 120, kcalPerPortion: 22, protein: 1.1, carbs: 4.8, fat: 0.2 },
  { name: 'Concombre', defaultPortionG: 120, kcalPerPortion: 18, protein: 0.8, carbs: 4, fat: 0.2 },
  { name: 'Épinards', defaultPortionG: 100, kcalPerPortion: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: 'Pizza margherita', defaultPortionG: 120, kcalPerPortion: 320, protein: 12, carbs: 38, fat: 13 },
  { name: 'Burger classique', defaultPortionG: 180, kcalPerPortion: 450, protein: 24, carbs: 37, fat: 23 },
  { name: 'Frites', defaultPortionG: 150, kcalPerPortion: 450, protein: 5, carbs: 53, fat: 22 },
  { name: 'Sushi saumon (6)', defaultPortionG: 180, kcalPerPortion: 220, protein: 12, carbs: 28, fat: 7 },
  { name: 'Wrap poulet', defaultPortionG: 220, kcalPerPortion: 420, protein: 24, carbs: 38, fat: 18 },
  { name: 'Soupe légumes', defaultPortionG: 300, kcalPerPortion: 120, protein: 4, carbs: 18, fat: 3 },
  { name: 'Croissant', defaultPortionG: 55, kcalPerPortion: 231, protein: 5, carbs: 26, fat: 12 },
  { name: 'Pain au chocolat', defaultPortionG: 75, kcalPerPortion: 330, protein: 6, carbs: 37, fat: 17 },
  { name: 'Biscuit sablé', defaultPortionG: 20, kcalPerPortion: 95, protein: 1.1, carbs: 11, fat: 5 },
  { name: 'Chocolat noir', defaultPortionG: 20, kcalPerPortion: 120, protein: 1.8, carbs: 6, fat: 9.5 },
  { name: 'Barre céréales', defaultPortionG: 25, kcalPerPortion: 98, protein: 1.7, carbs: 17, fat: 2.5 },
  { name: 'Jus d\'orange', defaultPortionG: 200, kcalPerPortion: 90, protein: 1.4, carbs: 20, fat: 0.4 },
  { name: 'Soda', defaultPortionG: 330, kcalPerPortion: 139, protein: 0, carbs: 35, fat: 0 },
  { name: 'Eau', defaultPortionG: 250, kcalPerPortion: 0, protein: 0, carbs: 0, fat: 0 },
  { name: 'Café sans sucre', defaultPortionG: 150, kcalPerPortion: 2, protein: 0.3, carbs: 0, fat: 0 },
  { name: 'Cappuccino', defaultPortionG: 250, kcalPerPortion: 95, protein: 5, carbs: 9, fat: 4 },
  { name: 'Smoothie fruits', defaultPortionG: 250, kcalPerPortion: 160, protein: 3, carbs: 35, fat: 1 },
  { name: 'Protéine whey', defaultPortionG: 30, kcalPerPortion: 120, protein: 24, carbs: 3, fat: 1.5 },
  { name: 'Poulet poêlé', defaultPortionG: 100, kcalPerPortion: 184, protein: 12.9, carbs: 0.5, fat: 14.5 },
  { name: 'Poulet au four', defaultPortionG: 100, kcalPerPortion: 168, protein: 11.8, carbs: 0.5, fat: 13.2 },
  { name: 'Poulet à la vapeur', defaultPortionG: 100, kcalPerPortion: 152, protein: 10.6, carbs: 0.5, fat: 12.0 },
  { name: 'Poulet pané', defaultPortionG: 100, kcalPerPortion: 216, protein: 15.1, carbs: 2, fat: 16.4 },
  { name: 'Dinde grillé', defaultPortionG: 100, kcalPerPortion: 160, protein: 11.2, carbs: 0.5, fat: 12.6 },
  { name: 'Dinde poêlé', defaultPortionG: 100, kcalPerPortion: 184, protein: 12.9, carbs: 0.5, fat: 14.5 },
  { name: 'Dinde au four', defaultPortionG: 100, kcalPerPortion: 168, protein: 11.8, carbs: 0.5, fat: 13.2 },
  { name: 'Dinde à la vapeur', defaultPortionG: 100, kcalPerPortion: 152, protein: 10.6, carbs: 0.5, fat: 12.0 },
  { name: 'Dinde pané', defaultPortionG: 100, kcalPerPortion: 216, protein: 15.1, carbs: 2, fat: 16.4 },
  { name: 'Bœuf grillé', defaultPortionG: 100, kcalPerPortion: 190, protein: 13.3, carbs: 0.5, fat: 15.0 },
  { name: 'Bœuf poêlé', defaultPortionG: 100, kcalPerPortion: 218, protein: 15.3, carbs: 0.5, fat: 17.2 },
  { name: 'Bœuf au four', defaultPortionG: 100, kcalPerPortion: 200, protein: 14.0, carbs: 0.5, fat: 15.8 },
  { name: 'Bœuf à la vapeur', defaultPortionG: 100, kcalPerPortion: 180, protein: 12.6, carbs: 0.5, fat: 14.2 },
  { name: 'Bœuf pané', defaultPortionG: 100, kcalPerPortion: 256, protein: 17.9, carbs: 2, fat: 19.6 },
  { name: 'Porc grillé', defaultPortionG: 100, kcalPerPortion: 190, protein: 13.3, carbs: 0.5, fat: 15.0 },
  { name: 'Porc poêlé', defaultPortionG: 100, kcalPerPortion: 218, protein: 15.3, carbs: 0.5, fat: 17.2 },
  { name: 'Porc au four', defaultPortionG: 100, kcalPerPortion: 200, protein: 14.0, carbs: 0.5, fat: 15.8 },
  { name: 'Porc à la vapeur', defaultPortionG: 100, kcalPerPortion: 180, protein: 12.6, carbs: 0.5, fat: 14.2 },
  { name: 'Porc pané', defaultPortionG: 100, kcalPerPortion: 256, protein: 17.9, carbs: 2, fat: 19.6 },
  { name: 'Saumon grillé', defaultPortionG: 100, kcalPerPortion: 208, protein: 14.6, carbs: 0.5, fat: 16.4 },
  { name: 'Saumon poêlé', defaultPortionG: 100, kcalPerPortion: 239, protein: 16.7, carbs: 0.5, fat: 18.9 },
  { name: 'Saumon au four', defaultPortionG: 100, kcalPerPortion: 218, protein: 15.3, carbs: 0.5, fat: 17.2 },
  { name: 'Saumon à la vapeur', defaultPortionG: 100, kcalPerPortion: 198, protein: 13.9, carbs: 0.5, fat: 15.6 },
  { name: 'Saumon pané', defaultPortionG: 100, kcalPerPortion: 281, protein: 19.7, carbs: 2, fat: 21.6 },
  { name: 'Thon grillé', defaultPortionG: 100, kcalPerPortion: 116, protein: 8.1, carbs: 0.5, fat: 9.1 },
  { name: 'Thon poêlé', defaultPortionG: 100, kcalPerPortion: 133, protein: 9.3, carbs: 0.5, fat: 10.4 },
  { name: 'Thon au four', defaultPortionG: 100, kcalPerPortion: 122, protein: 8.5, carbs: 0.5, fat: 9.6 },
  { name: 'Thon à la vapeur', defaultPortionG: 100, kcalPerPortion: 110, protein: 7.7, carbs: 0.5, fat: 8.6 },
  { name: 'Thon pané', defaultPortionG: 100, kcalPerPortion: 157, protein: 11.0, carbs: 2, fat: 11.7 },
  { name: 'Crevettes grillé', defaultPortionG: 100, kcalPerPortion: 99, protein: 6.9, carbs: 0.5, fat: 7.7 },
  { name: 'Crevettes poêlé', defaultPortionG: 100, kcalPerPortion: 114, protein: 8.0, carbs: 0.5, fat: 8.9 },
  { name: 'Crevettes au four', defaultPortionG: 100, kcalPerPortion: 104, protein: 7.3, carbs: 0.5, fat: 8.1 },
  { name: 'Crevettes à la vapeur', defaultPortionG: 100, kcalPerPortion: 94, protein: 6.6, carbs: 0.5, fat: 7.3 },
  { name: 'Crevettes pané', defaultPortionG: 100, kcalPerPortion: 134, protein: 9.4, carbs: 2, fat: 9.8 },
  { name: 'Tofu grillé', defaultPortionG: 100, kcalPerPortion: 145, protein: 10.2, carbs: 0.5, fat: 11.4 },
  { name: 'Tofu poêlé', defaultPortionG: 100, kcalPerPortion: 167, protein: 11.7, carbs: 0.5, fat: 13.1 },
  { name: 'Tofu au four', defaultPortionG: 100, kcalPerPortion: 152, protein: 10.6, carbs: 0.5, fat: 12.0 },
  { name: 'Tofu à la vapeur', defaultPortionG: 100, kcalPerPortion: 138, protein: 9.7, carbs: 0.5, fat: 10.8 },
  { name: 'Tofu pané', defaultPortionG: 100, kcalPerPortion: 196, protein: 13.7, carbs: 2, fat: 14.8 },
  { name: 'Tempeh grillé', defaultPortionG: 100, kcalPerPortion: 195, protein: 13.7, carbs: 0.5, fat: 15.4 },
  { name: 'Tempeh poêlé', defaultPortionG: 100, kcalPerPortion: 224, protein: 15.7, carbs: 0.5, fat: 17.7 },
  { name: 'Tempeh au four', defaultPortionG: 100, kcalPerPortion: 205, protein: 14.4, carbs: 0.5, fat: 16.2 },
  { name: 'Tempeh à la vapeur', defaultPortionG: 100, kcalPerPortion: 185, protein: 13.0, carbs: 0.5, fat: 14.6 },
  { name: 'Tempeh pané', defaultPortionG: 100, kcalPerPortion: 263, protein: 18.4, carbs: 2, fat: 20.2 },
  { name: 'Œufs brouillés grillé', defaultPortionG: 100, kcalPerPortion: 170, protein: 11.9, carbs: 0.5, fat: 13.4 },
  { name: 'Œufs brouillés poêlé', defaultPortionG: 100, kcalPerPortion: 195, protein: 13.7, carbs: 0.5, fat: 15.4 },
  { name: 'Œufs brouillés au four', defaultPortionG: 100, kcalPerPortion: 178, protein: 12.5, carbs: 0.5, fat: 14.0 },
  { name: 'Œufs brouillés à la vapeur', defaultPortionG: 100, kcalPerPortion: 162, protein: 11.3, carbs: 0.5, fat: 12.8 },
  { name: 'Œufs brouillés pané', defaultPortionG: 100, kcalPerPortion: 230, protein: 16.1, carbs: 2, fat: 17.5 },
  { name: 'Riz blanc al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Riz blanc sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Riz blanc en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Riz blanc portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Riz basmati cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Riz basmati al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Riz basmati sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Riz basmati en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Riz basmati portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Riz complet al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Riz complet sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Riz complet en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Riz complet portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Pâtes blanches cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Pâtes blanches al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Pâtes blanches sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Pâtes blanches en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Pâtes blanches portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Pâtes complètes cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Pâtes complètes al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Pâtes complètes sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Pâtes complètes en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Pâtes complètes portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Quinoa al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Quinoa sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Quinoa en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Quinoa portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Boulgour cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Boulgour al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Boulgour sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Boulgour en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Boulgour portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Semoule cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Semoule al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Semoule sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Semoule en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Semoule portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Pommes de terre cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Pommes de terre al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Pommes de terre sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Pommes de terre en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Pommes de terre portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Patate douce cuit', defaultPortionG: 100, kcalPerPortion: 120, protein: 3, carbs: 24, fat: 1.2 },
  { name: 'Patate douce al dente', defaultPortionG: 100, kcalPerPortion: 114, protein: 3, carbs: 22.8, fat: 1.1 },
  { name: 'Patate douce sauté', defaultPortionG: 100, kcalPerPortion: 144, protein: 3, carbs: 28.8, fat: 1.4 },
  { name: 'Patate douce en salade', defaultPortionG: 100, kcalPerPortion: 108, protein: 3, carbs: 21.6, fat: 1.1 },
  { name: 'Patate douce portion sportive', defaultPortionG: 100, kcalPerPortion: 168, protein: 3, carbs: 33.6, fat: 1.7 },
  { name: 'Brocoli cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Brocoli cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Brocoli poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Brocoli rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Brocoli surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Haricots verts cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Haricots verts cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Haricots verts poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Haricots verts rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Haricots verts surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Épinards cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Épinards cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Épinards poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Épinards rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Épinards surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Courgette cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Courgette cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Courgette poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Courgette rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Courgette surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Aubergine cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Aubergine cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Aubergine poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Aubergine rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Aubergine surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Poivron cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Poivron cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Poivron poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Poivron rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Poivron surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Champignons cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Champignons cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Champignons poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Champignons rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Champignons surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Chou-fleur cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Chou-fleur cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Chou-fleur poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Chou-fleur rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Chou-fleur surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Tomate cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Tomate cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Tomate poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Tomate rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Tomate surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Concombre cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Concombre cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Concombre poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Concombre rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Concombre surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Carotte cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Carotte cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Carotte poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Carotte rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Carotte surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Asperges cru', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Asperges cuit vapeur', defaultPortionG: 100, kcalPerPortion: 27, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Asperges poêlé', defaultPortionG: 100, kcalPerPortion: 38, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Asperges rôti', defaultPortionG: 100, kcalPerPortion: 34, protein: 2, carbs: 4, fat: 0.6 },
  { name: 'Asperges surgelé', defaultPortionG: 100, kcalPerPortion: 30, protein: 2, carbs: 4, fat: 0.5 },
  { name: 'Pomme petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Pomme moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Pomme grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Pomme en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Banane petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Banane moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Banane grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Banane en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Poire petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Poire moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Poire grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Poire en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Orange petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Orange moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Orange grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Orange en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Kiwi petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Kiwi moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Kiwi grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Kiwi en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Mangue petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Mangue moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Mangue grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Mangue en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Ananas petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Ananas moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Ananas grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Ananas en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Raisin petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Raisin moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Raisin grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Raisin en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Framboises petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Framboises moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Framboises grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Framboises en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Myrtilles petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Myrtilles moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Myrtilles grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Myrtilles en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Fraise petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Fraise moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Fraise grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Fraise en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Melon petit', defaultPortionG: 100, kcalPerPortion: 55, protein: 1, carbs: 13.1, fat: 0.3 },
  { name: 'Melon moyen', defaultPortionG: 140, kcalPerPortion: 75, protein: 1, carbs: 17.9, fat: 0.3 },
  { name: 'Melon grand', defaultPortionG: 180, kcalPerPortion: 98, protein: 1, carbs: 23.3, fat: 0.3 },
  { name: 'Melon en dés', defaultPortionG: 120, kcalPerPortion: 70, protein: 1, carbs: 16.7, fat: 0.3 },
  { name: 'Amandes mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Amandes standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Amandes large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Noix de cajou mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Noix de cajou standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Noix de cajou large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Noisettes mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Noisettes standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Noisettes large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Pistaches mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Pistaches standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Pistaches large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Crackers mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Crackers standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Crackers large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Pop-corn mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Pop-corn standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Pop-corn large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Chips mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Chips standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Chips large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Galette de riz mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Galette de riz standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Galette de riz large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Yaourt grec mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Yaourt grec standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Yaourt grec large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
  { name: 'Compote sans sucre mini', defaultPortionG: 15, kcalPerPortion: 65, protein: 4, carbs: 8, fat: 9 },
  { name: 'Compote sans sucre standard', defaultPortionG: 30, kcalPerPortion: 130, protein: 4, carbs: 8, fat: 9 },
  { name: 'Compote sans sucre large', defaultPortionG: 45, kcalPerPortion: 195, protein: 4, carbs: 8, fat: 9 },
];
